export const MyAction = {
  EVENT: "EVNETFETCHING",
  RECEIVEDEVENT: "RECEIVEDEVNET",

  GETVIEWPORT: "GETVIEWPORT",
  SETVIEWPORT: "SETVIEWPORT",

  GETLOCATION: "GETLOCATION",
  SETLOCATION: "SETLOCATION",

  GETFEED: "GETFEED",
  SETFEED: "SETFEED"
};
